### ISSUE TITLE
Change TID/SID code for FireRed 1.0  is causing player data corruption

### ISSUE THREAD

**Issue by Bubblemeister** [E-Sh4rk/EmeraldACE_web#24] opened 2024-11-07 19:27 UTC
When using the TID/SID generator with CommonExit for crobat move ace on FireRed 1.0, there seems to be 2 separate issues.
The first is that the TID and SID fields seem to be swapped as my inputted SID gets set as my Trainer ID and is visible on the trainer Card.
The second and more important issue is that it seems to corrupt the player data as the trainers gender is swapped on most executions of the Ace code. I have also run into the issue of the players sprite being changed to a rocket grunt and save location being changed on reloading the game as after saving in route 1, upon reload i was spawned inside the union room with the location displaying as celadon dept store.
I have tested this on both BIzhawk 2.9.1 (x64) and mGBA 0.10.3 and had the same results on both.

**Comment by Bubblemeister** [comment] 2024-11-07 19:28
This is also a new issue as before the commit where Grab ace was added this was working fine

**Comment by E-Sh4rk** [comment] 2024-11-07 20:03
@papajefe Any idea on what's going on?

I cannot investigate right now, but if the TID got the SID value I guess that means the writes are 2 bytes off. This seems coherent with the modifications made by the last commit.

Can you tell me if it works with this assembly? (I just changed the offset of the two `strh r11, [r12, xx]` lines)
```
sbc r12, r15, #0xd100
movs r11, {tid} ?
strh r11, [r12, #0x34] 
movs r11, {sid} ?
strh r11, [r12, #0x36] 
```

**Comment by E-Sh4rk** [comment] 2024-11-07 20:25
My guess is that it is not an emulator vs console issue, but a GrabACE vs MoveACE issue.

The status of the CPSR regsiter may be different depending on the ACE method (in particular the Carry flag), which would make the first command (`sbc`) to do an additional -1 with GrabACE compared to MoveACE. I will make a separate code for MoveACE with the additional offset.

**Comment by papajefe** [comment] 2024-11-07 20:32
I figured out what I did wrong. 

The old MoveACE code was as follows:

`sbc r0, pc, #0xE2
sbcs r12, r15, #0xd100
movs r11, {tid} ?
strh r11, [r12, #0x30] 
movs r11, {sid} ?
strh r11, [r12, #0x32] `

The extra `sbc r0, pc, #0xE2` was totally unnecessary as I thought, but removing it changed to location of pc when that line was ready, and I didn't shift the offsets correctly. I thought they lined up with the GrabACE code, but I didn't account for the carry flag difference.

**Comment by E-Sh4rk** [comment] 2024-11-07 20:36
I see, that's what I was thinking too :)

I updated the code, I think it can still work for both ACE methods if we use the offsets `0x33` and `0x35`.
I'll close the issue but don't hesitate to answer if it does not solve it.

**Closed by E-Sh4rk** 2024-11-07 20:36 UTC

**Comment by papajefe** [comment] 2024-11-07 20:52
#0x33 / #0x35 seemed to work fine for Crobat MoveACE 
[Crobat TID SID_33-35.zip](https://github.com/user-attachments/files/17669252/Crobat.TID.SID_33-35.zip)
[Grab TID SID_33-35.zip](https://github.com/user-attachments/files/17669296/Grab.TID.SID_33-35.zip)

However, when I tried those offsets with GrabACEExit using TID=54321 and SID=12
I got SID = 54321 and PlayTime Hours = 12345

**Comment by E-Sh4rk** [comment] 2024-11-07 21:04
Ok so I guess the discrepancy between GrabACE and MoveACE does not come from the CPSR register but from the pc register misalignment. I'll make two separate codes then, and I'll explain in more detail after that.

**Comment by E-Sh4rk** [comment] 2024-11-07 21:26
Ok so for the explanations, there were two possible discrepancies between the ACE methods:

- The first is the status of the CPSR register. If the Carry flag is set to 0 when executing the ACE code, then the `sbc` command does an additional -1 (if it is set to 1 instead then it just does the amount written with no additional offset). Also, note that if the `strh` command is given an odd destination address, it rounds it to the least even address. But if it was the cause of the issue, then using the offsets `0x33` and `0x35` would have solved it.

- The second possible discrepancy is what we call the "PC register misalignment". When in ARM mode, the PC register is supposed to always be a multiple of 4 bytes (as ARM commands are all 4 bytes). But some ACE methods mess up the PC register with an invalid jump (in particular this is the case of ARM sprite animation ACE in emerald, and it seems to be the case of Grab ACE in FRLG too), which makes the PC register to be always be aligned with a multiple of 4 + an offset of 2. These two additional bytes are ignored when loading the next ARM command, but they do count when doing arithmetic based on the PC register. This explains why with Grab ACE we ended up writing 2 bytes after compared to Move ACE.

**Comment by papajefe** [comment] 2024-11-07 22:19
Appreciate the explanation. I'd still be lost w/o you and Shao's help. you're awesome :)
